// 整句庫：生活篇 50 句、職場會議篇 50 句，各分 5 級（由短到長、連音與縮寫由少到多）。
// 全部原創的日常口語句子。id 一旦用過就不要改（作答紀錄靠 id 對應）。
// 新增句子：在對應的段落加一行，給一個沒用過的 id 即可。
var SENTENCES = (function () {
  var L = [
    // ---------- 生活篇 ----------
    ["L001", "life", 1, "How's it going?", "最近好嗎？"],
    ["L002", "life", 1, "I'll be right back.", "我馬上回來。"],
    ["L003", "life", 1, "Can I get a coffee?", "可以給我一杯咖啡嗎？"],
    ["L004", "life", 1, "What do you want to eat?", "你想吃什麼？"],
    ["L005", "life", 1, "Let me think about it.", "讓我想一想。"],
    ["L006", "life", 1, "Do you have a minute?", "你有空一下嗎？"],
    ["L007", "life", 1, "I'm on my way.", "我在路上了。"],
    ["L008", "life", 1, "It's not a big deal.", "沒什麼大不了的。"],
    ["L009", "life", 1, "Could you say that again?", "可以再說一次嗎？"],
    ["L010", "life", 1, "Sorry, I didn't catch that.", "抱歉，我沒聽清楚。"],
    ["L011", "life", 2, "I'm going to grab something to eat.", "我要去隨便吃點東西。"],
    ["L012", "life", 2, "What are you up to this weekend?", "你這週末要做什麼？"],
    ["L013", "life", 2, "Do you want me to pick you up?", "要我去接你嗎？"],
    ["L014", "life", 2, "I'll text you when I get there.", "我到了再傳訊息給你。"],
    ["L015", "life", 2, "It's been a long day at work.", "今天上班好累。"],
    ["L016", "life", 2, "Can I get the check, please?", "麻煩買單。"],
    ["L017", "life", 2, "How long have you been waiting?", "你等多久了？"],
    ["L018", "life", 2, "I think I left my phone in the car.", "我好像把手機忘在車上了。"],
    ["L019", "life", 2, "We should get together sometime soon.", "我們找時間聚一聚吧。"],
    ["L020", "life", 2, "Is it okay if I sit here?", "我可以坐這裡嗎？"],
    ["L021", "life", 3, "I was going to call you, but I forgot.", "我本來要打給你，結果忘了。"],
    ["L022", "life", 3, "Could you turn it down a little bit?", "可以把聲音關小一點嗎？"],
    ["L023", "life", 3, "Let me know if you need any help with that.", "那件事需要幫忙的話跟我說。"],
    ["L024", "life", 3, "I've been meaning to ask you about it.", "我一直想問你這件事。"],
    ["L025", "life", 3, "What time does the store close on Sundays?", "這家店星期天幾點關門？"],
    ["L026", "life", 3, "I'd like to make a reservation for four people.", "我想訂四個人的位子。"],
    ["L027", "life", 3, "We ran out of milk, so I'll get some on the way home.", "牛奶喝完了，我回家路上買。"],
    ["L028", "life", 3, "Do you mind if I open the window?", "你介意我開窗嗎？"],
    ["L029", "life", 3, "I can't make it tonight, but how about tomorrow?", "我今晚沒辦法，明天呢？"],
    ["L030", "life", 3, "It took me an hour to get here because of the traffic.", "因為塞車，我花了一小時才到。"],
    ["L031", "life", 4, "If I'd known it was going to rain, I would've brought an umbrella.", "早知道會下雨，我就帶傘了。"],
    ["L032", "life", 4, "I don't know what it is, but something doesn't feel right.", "說不上來為什麼，但感覺怪怪的。"],
    ["L033", "life", 4, "Would you mind keeping an eye on my bag for a second?", "可以幫我顧一下包包嗎？"],
    ["L034", "life", 4, "I've got to get up early tomorrow, so I'd better head home.", "我明天要早起，最好先回家了。"],
    ["L035", "life", 4, "Have you had a chance to look at the photos I sent you?", "你有空看我傳給你的照片了嗎？"],
    ["L036", "life", 4, "She told me she'd be here by six, but she isn't here yet.", "她說六點前會到，但還沒來。"],
    ["L037", "life", 4, "We're thinking about going out of town for a couple of days.", "我們在考慮出城玩個兩三天。"],
    ["L038", "life", 4, "I ended up staying at home and watching TV all afternoon.", "結果我整個下午都待在家看電視。"],
    ["L039", "life", 4, "Can you give me a hand with these boxes? They're heavier than they look.", "可以幫我搬這些箱子嗎？比看起來重。"],
    ["L040", "life", 4, "I'm not sure what I want to order. What would you recommend?", "我不知道要點什麼，你推薦什麼？"],
    ["L041", "life", 5, "I should've checked the weather before we left, but I didn't think it'd change that fast.", "出門前應該看一下天氣的，沒想到變得這麼快。"],
    ["L042", "life", 5, "Let's just wait and see what happens, and we can figure it out from there.", "先看看會怎樣，再從那邊想辦法。"],
    ["L043", "life", 5, "He's been working on that project for months, and he still hasn't finished it.", "他那個案子做了好幾個月，到現在還沒做完。"],
    ["L044", "life", 5, "I didn't mean to make you wait. The meeting ran a lot longer than I thought it would.", "不是故意讓你等的，會議比我想的拖了好久。"],
    ["L045", "life", 5, "If you're not doing anything later, do you want to get a bite to eat?", "你等一下沒事的話，要不要一起吃點東西？"],
    ["L046", "life", 5, "I'd have gone with them if I hadn't had so much to do at home.", "要不是家裡事情那麼多，我就跟他們去了。"],
    ["L047", "life", 5, "What I'm trying to say is that we don't have to decide right now.", "我的意思是，我們不用現在就決定。"],
    ["L048", "life", 5, "It's not that I don't want to go; it's just that I'm a little tired.", "不是我不想去，只是有點累。"],
    ["L049", "life", 5, "You could've told me earlier. I would've been happy to help out.", "你可以早點跟我說，我很樂意幫忙的。"],
    ["L050", "life", 5, "Whatever you decide, let me know, and I'll go along with it.", "不管你怎麼決定，跟我說一聲，我都配合。"],
    // ---------- 職場會議篇 ----------
    ["M001", "meeting", 1, "Can everyone hear me?", "大家聽得到我嗎？"],
    ["M002", "meeting", 1, "Let's get started.", "我們開始吧。"],
    ["M003", "meeting", 1, "Any questions so far?", "到目前為止有問題嗎？"],
    ["M004", "meeting", 1, "I'll send you the slides.", "我會把投影片寄給你。"],
    ["M005", "meeting", 1, "Could you share your screen?", "可以分享你的畫面嗎？"],
    ["M006", "meeting", 1, "Sorry, you're on mute.", "抱歉，你現在是靜音。"],
    ["M007", "meeting", 1, "Let's take a short break.", "我們休息一下。"],
    ["M008", "meeting", 1, "That's a good point.", "這點說得很好。"],
    ["M009", "meeting", 1, "I'll follow up by email.", "我會再寫信追蹤。"],
    ["M010", "meeting", 1, "Let's wrap it up.", "我們收尾吧。"],
    ["M011", "meeting", 2, "Thanks for joining the call today.", "謝謝大家今天參加會議。"],
    ["M012", "meeting", 2, "Can we go back to the last slide?", "可以回到上一張投影片嗎？"],
    ["M013", "meeting", 2, "I'd like to add something to that.", "我想補充一點。"],
    ["M014", "meeting", 2, "Let's move on to the next item.", "我們進行下一個議題。"],
    ["M015", "meeting", 2, "Who's going to take care of this?", "這件事誰來負責？"],
    ["M016", "meeting", 2, "What's the deadline for this project?", "這個案子的期限是什麼時候？"],
    ["M017", "meeting", 2, "Could you walk us through the numbers?", "可以帶我們看一下這些數字嗎？"],
    ["M018", "meeting", 2, "I'm afraid I have to disagree with that.", "恐怕我不同意這一點。"],
    ["M019", "meeting", 2, "Let's schedule another meeting next week.", "我們下週再約一次會議。"],
    ["M020", "meeting", 2, "Does that make sense to everyone?", "大家都清楚嗎？"],
    ["M021", "meeting", 3, "Before we start, let's go over today's agenda.", "開始前，我們先看一下今天的議程。"],
    ["M022", "meeting", 3, "I just want to make sure we're on the same page.", "我只是想確認大家的理解一致。"],
    ["M023", "meeting", 3, "We're running a little behind, so let's keep it short.", "時間有點落後，我們長話短說。"],
    ["M024", "meeting", 3, "Could you give us a quick update on where things stand?", "可以簡單更新一下目前進度嗎？"],
    ["M025", "meeting", 3, "I'll get back to you on that by the end of the day.", "這件事我今天下班前回覆你。"],
    ["M026", "meeting", 3, "Let's put that on hold until we have more information.", "等資訊多一點再說，先暫停。"],
    ["M027", "meeting", 3, "I think we need to push the deadline back a week.", "我想期限需要延後一週。"],
    ["M028", "meeting", 3, "Can you send me a summary after the meeting?", "會後可以寄一份摘要給我嗎？"],
    ["M029", "meeting", 3, "We don't have enough budget to do all of it this quarter.", "這一季的預算不夠全部都做。"],
    ["M030", "meeting", 3, "Who's responsible for getting in touch with the client?", "誰負責聯絡客戶？"],
    ["M031", "meeting", 4, "I'm not sure we have time to cover that today, so let's take it offline.", "今天可能沒時間討論那個，我們會後再私下談。"],
    ["M032", "meeting", 4, "Just to clarify, are we talking about this month or next month?", "確認一下，我們說的是這個月還是下個月？"],
    ["M033", "meeting", 4, "It looks like sales went up about ten percent compared to last year.", "看起來銷售比去年成長了大約一成。"],
    ["M034", "meeting", 4, "I'd like to hear what the rest of the team thinks before we decide.", "決定之前，我想聽聽團隊其他人的想法。"],
    ["M035", "meeting", 4, "We've already talked about this, so let's focus on the next steps.", "這個已經討論過了，我們專心談下一步。"],
    ["M036", "meeting", 4, "If there aren't any other questions, I think we can end a few minutes early.", "如果沒有其他問題，我們可以提早幾分鐘結束。"],
    ["M037", "meeting", 4, "Sorry to interrupt, but could you explain what you meant by that?", "抱歉打斷一下，可以解釋你剛剛的意思嗎？"],
    ["M038", "meeting", 4, "We should've raised this issue earlier, but it's not too late to fix it.", "這個問題應該早點提出來，不過現在修正還來得及。"],
    ["M039", "meeting", 4, "Let me check with my manager and get back to you tomorrow.", "我跟主管確認一下，明天回覆你。"],
    ["M040", "meeting", 4, "Can we set up a quick call with the vendor sometime this week?", "這週可以跟廠商約個簡短的電話會議嗎？"],
    ["M041", "meeting", 5, "The main reason we're behind schedule is that we didn't get the data we needed on time.", "進度落後的主因是我們沒有準時拿到需要的資料。"],
    ["M042", "meeting", 5, "What I'd suggest is that we start with a small test and see how it goes before we roll it out.", "我建議先小規模測試，看看效果再全面推行。"],
    ["M043", "meeting", 5, "I understand your concern, but I think the benefits outweigh the risks in this case.", "我理解你的顧慮，但這次我認為好處大於風險。"],
    ["M044", "meeting", 5, "If we can't agree on the budget by Friday, we'll have to put the whole project on hold.", "如果星期五前預算談不攏，整個案子就得暫停。"],
    ["M045", "meeting", 5, "Let's make sure everyone knows who's doing what, and when it needs to be done.", "我們要確定每個人都知道誰做什麼、什麼時候要完成。"],
    ["M046", "meeting", 5, "I was under the impression that the client had already signed off on the design.", "我原本以為客戶已經核准設計了。"],
    ["M047", "meeting", 5, "We've got a lot to get through today, so I'm going to try to keep things moving.", "今天要討論的很多，我會盡量讓會議順暢進行。"],
    ["M048", "meeting", 5, "It'd be helpful if you could send over the latest numbers before the meeting on Thursday.", "如果你能在星期四開會前把最新數字寄過來會很有幫助。"],
    ["M049", "meeting", 5, "Going forward, I think we should check in once a week instead of once a month.", "之後我認為我們應該每週確認一次，而不是每月一次。"],
    ["M050", "meeting", 5, "Could you go over that last part again? I want to make sure I didn't miss anything.", "最後那部分可以再講一次嗎？我想確定我沒漏掉什麼。"]
  ];
  return L.map(function (r, k) { return {id: r[0], set: r[1], level: r[2], en: r[3], zh: r[4], n: k}; });
})();
if (typeof module !== "undefined" && module.exports) module.exports = SENTENCES;
